version: '3.8'

services:
  api:
    build: ./app
    command: python3 manage.py runserver 0.0.0.0:9000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 9000:9000
    env_file:
      - ./.cot-api
    container_name: 'api_user-reg'
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    container_name: 'db_cotizate'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
        - ./app/.cot-db

volumes:
  postgres_data:
