version: '3.8'

services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn api.wsgi:application --bind 0.0.0.0:9000
    expose:
      - 9000
    env_file:
      - ./.cot-api
    container_name: 'api_user-reg'
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    container_name: 'db_cotizate'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
        - ./app/.cot-db

  nginx:
    build: ./nginx
    ports:
      - 9001:80
    depends_on:
      - api

volumes:
  postgres_data:
